# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# This yaml file was create for the purpose of building a custom image for the International Ingles school.
# Any questions or issues can be directed to the e-mail: niltonperimneto@gmail.com
# The image is based on Fedora Kinoite and includes various educational tools and software.

name: inglesinternational-os
description: This is a custom image made for the International Ingles school focused on an educational environment.
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 42

modules:
  - type: files
    files:
      - source: system
        destination: /
      - source: system/usr
        destination: /usr
      - source: system/etc
        destination: /etc

  - type: rpm-ostree
    install:
      - code
      - google-chrome-stable
      - python3-pip
    keys:
      - https://packages.microsoft.com/keys/microsoft.asc
      - https://dl.google.com/linux/linux_signing_key.pub

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: user
          repo:
        title: Flathub (user)
        install:
          - com.usebottles.bottles
          - it.mijorus.gearlever
          - com.github.tchx84.Flatseal
          - com.mojang.Minecraft
          - io.dbeaver.DBeaverCommunity
          - edu.mit.Scratch
          - org.onlyoffice.desktopeditors
          - org.vinegarhq.Vinegar
          - io.github.shiftey.Desktop
          - io.github.dvlv.boxbuddyrs

  - type: signing
