# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# This yaml file was create for the purpose of building a custom image for the International Ingles school.
# Any questions or issues can be directed to the github repo or to the e-mail adress: niltonperimneto@gmail.com
# The image is based on Fedora Kinoite and includes various educational tools and software.

name: interlinux
description: This is a custom image made for the International Ingles school focused on an educational environment.
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 42

modules:
  - type: os-release
    properties:
      ID: internationallinux-os
      ID_LIKE: fedora
      NAME: International Linux OS
      PRETTY_NAME: International Linux OS
      #VERSION: 2025
      #ANSI_COLOR: 0;38;2;60;110;180
      #LOGO: example-logo
      #HOME_URL: https://kinoite.fedoraproject.org
      DOCUMENTATION_URL: https://docs.fedoraproject.org/en-US/fedora

  - type: files
    files:
      - source: system
        destination: /
      - source: system/usr
        destination: /usr
      - source: system/etc
        destination: /etc

  - type: rpm-ostree
    keys:
      - https://packages.microsoft.com/keys/microsoft.asc
    install:
      - code
      - git
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-42.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-42.noarch.rpm
      - python3-pip
      - micro
      - fish
    remove:
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - com.usebottles.bottles
          - io.github.kolunmi.Bazaar
          - it.mijorus.gearlever
          - com.github.tchx84.Flatseal
          - com.mojang.Minecraft
          - io.dbeaver.DBeaverCommunity
          - edu.mit.Scratch
          - org.onlyoffice.desktopeditors
          - org.vinegarhq.Vinegar
          - io.github.shiftey.Desktop
          - io.github.dvlv.boxbuddyrs
          - com.jetbrains.PyCharm-Community
          - com.google.Chrome
      - scope: user

  - type: script
    scripts:
      - setfish.sh
      - setmicro.sh

  - type: signing
